student_info/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^students/', include("students.urls", namespace="students")),
]

students/urls.py
from django.conf.urls import  url

from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^students/(?P<id>\d+)/$', views.students, name='detail'),
]

students/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Student (models.Model):
    name = models.CharField(max_length = 100)
    created = models.DateTimeField(auto_now_add=True)
    bio = models.TextField(blank=True)
    github_url = models.URLField(max_length=200)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ("students:detail", kwargs={"id":self.pk})

students/views.py
from django.shortcuts import render, get_object_or_404

from .models import Student


def index (request):
    students = Student.objects.all()

    context = {
        "students": students
    }

    return render (request, "students/index.html", context)


def students (request, id):
    students = get_object_or_404(Student, pk=id)

    context = {
        "students":students
    }

    return render (request, "students/student.html", context)

students/templates/students/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            Students
        {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'students/styles.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
                <a href="{% url 'students:index' %}" class="navbar-brand">
                    Students
                </a>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Awesome Inc U. Bootcamp 2016
        </div>
    </footer>

    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

students/templates/students/index.html
{% extends "students/base.html" %}

{% block title %}
    {{ block.super }}
    - Index
{% endblock title %}

{% block content %}

    <ul class="list-group">
        {% for student in students %}
            <li class="list-group-item">
                    <a href="{{student.get_absolute_url}}">
                        {{student.name}}               
                    </a>
            </li>
        {% endfor %}
    </ul>

{% endblock content %}

students/templates/students/student.html
{% extends "students/base.html" %}

{% block title %}
    {{ block.super }}
    - Student
{% endblock title %}

{% block content %}
    <h2>
        {{ students.name }}
    </h2>
    {% if students.bio %}
        Bio: <pre>{{ students.bio }}</pre>
    {% endif %}
    GitHub: <pre><a href="{{ students.github_url }}">{{ students.github_url }}</a></pre>
    Created: <pre>{{ students.created }}</pre>
{% endblock content %}